config/routes.rb
FoodBank::Application.routes.draw do

  resources :users
  resources :user_sessions

  resources :food_parcels do
    
  end

  resources :expenditures

  resources :food_donations do

  end

  resources :products

  resources :financial_donations

  resources :donors

  resources :addresses
  resources :referring_agencies
  
  resources :households do
    resources :other_occupants
  end
  
  match 'reporting/weight_total', :to => 'reporting#weight_total', :via => :get
  match 'reporting/update_weight', :to => 'reporting#update_weight', :via => :post
  match 'reporting/parcels_by_time_period', :to => 'reporting#parcels_by_time_period', :via => [:get, :post]
  match 'reporting/parcels_by_time_period_and_postcode', :to => 'reporting#parcels_by_time_period_and_postcode', :via => [:get, :post]  
  match 'reporting/households_with_multiple_parcels_by_time_period', :to => 'reporting#households_with_multiple_parcels_by_time_period', :via => [:get, :post]
  match 'reporting/food_donations_by_time_period', :to => 'reporting#food_donations_by_time_period', :via => [:get, :post]
  match 'reporting/food_donations_by_donor', :to => 'reporting#food_donations_by_donor', :via => [:get, :post]
    match 'reporting/inactive_households', :to => 'reporting#inactive_households', :via => [:get, :post]

  root :to => 'home#index'

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  
end

app/models/donor.rb
class Donor < ActiveRecord::Base
  acts_as_reportable
  
  has_many :food_donations, :dependent => :destroy
  has_many :financial_donations, :dependent => :destroy

  belongs_to :address, :dependent => :destroy
  belongs_to :contact_information, :dependent => :destroy
  
  accepts_nested_attributes_for :address, :allow_destroy => true
  accepts_nested_attributes_for :contact_information, :allow_destroy => true
  
  attr_accessible :name, :address_attributes, :contact_information_attributes
  
  validates :name, :presence => true
  
  def to_s
    self.name
  end
  
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  # GET /donors
  # GET /donors.json
  def index
    @donors = Donor.paginate :page => params[:page], :per_page => 20, :order => :name

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @donors }
    end
  end

  # GET /donors/1
  # GET /donors/1.json
  def show
    @donor = Donor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @donor }
    end
  end

  # GET /donors/new
  # GET /donors/new.json
  def new
    @donor = Donor.new
    @donor.build_address
    @donor.build_contact_information


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @donor }
    end
  end

  # GET /donors/1/edit
  def edit
    @donor = Donor.find(params[:id])
  end

  # POST /donors
  # POST /donors.json
  def create
    @donor = Donor.new(params[:donor])

    respond_to do |format|
      if @donor.save
        format.html { redirect_to @donor, notice: 'Donor was successfully created.' }
        format.json { render json: @donor, status: :created, location: @donor }
      else
        format.html { render action: "new" }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /donors/1
  # PUT /donors/1.json
  def update
    @donor = Donor.find(params[:id])

    respond_to do |format|
      if @donor.update_attributes(params[:donor])
        format.html { redirect_to @donor, notice: 'Donor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donors/1
  # DELETE /donors/1.json
  def destroy
    @donor = Donor.find(params[:id])
    @donor.destroy

    respond_to do |format|
      format.html { redirect_to donors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/views/donors/_form.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>
<% @donor.errors.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <%= content_tag :div, t(name) + " " + msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

<%= form_for @donor, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <%= f.fields_for :contact_information do |contact_information_form| %>
    <%= render :partial => 'common/contact_information_fields', :locals => { :contact_information_form => contact_information_form } %>
  <% end %>
  <hr/>
  <%= f.fields_for :address do |address_form| %>
    <%= render :partial => 'common/address_fields', :locals => { :address_form => address_form } %>
  <% end %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                donors_path, :class => 'btn' %>
  </div>
<% end %>

app/views/donors/edit.html.erb
<%- model_class = @donor.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/donors/index.html.erb
<%- model_class = Donor.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:address_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
	<%= page_entries_info @donors %>
	<%= will_paginate @donors, :renderer => BootstrapPagination::Rails %>	  
    <% @donors.each do |donor| %>
      <tr>
        <td><%= link_to donor.name, donor_path(donor) %></td>
        <td><%= donor.address %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_donor_path(donor), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      donor_path(donor),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_donor_path,
            :class => 'btn btn-primary' %>

app/views/donors/new.html.erb
<%- model_class = @donor.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/donors/show.html.erb
<%- model_class = @donor.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @donor.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @donor.address %></dd>
  <% if @donor.contact_information.email? %>
    <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
    <dd><%= @donor.contact_information.email %></dd>
  <% end %>
  <% if @donor.contact_information.telephone? %>
    <dt><strong><%= model_class.human_attribute_name(:telephone) %>:</strong></dt>
    <dd><%= @donor.contact_information.telephone %></dd>
  <% end %>
  <% if @donor.contact_information.mobile? %>
    <dt><strong><%= model_class.human_attribute_name(:mobile) %>:</strong></dt>
    <dd><%= @donor.contact_information.mobile %></dd>
  <% end %>
  <% if @donor.contact_information.facsimile? %>
    <dt><strong><%= model_class.human_attribute_name(:facsimile) %>:</strong></dt>
    <dd><%= @donor.contact_information.facsimile %></dd>
  <% end %>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              donors_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_donor_path(@donor), :class => 'btn' %>
  <%= link_to t(:create_food_donation), new_food_donation_path(:donor => @donor), :class => 'btn' %>
  <%= link_to t(:create_cash_donation), new_financial_donation_path(:donor => @donor), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              donor_path(@donor),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>