config/routes.rb
FoodBank::Application.routes.draw do

  resources :users
  resources :user_sessions

  resources :food_parcels do
    
  end

  resources :expenditures

  resources :food_donations do

  end

  resources :products

  resources :financial_donations

  resources :donors

  resources :addresses
  resources :referring_agencies
  
  resources :households do
    resources :other_occupants
  end
  
  match 'reporting/weight_total', :to => 'reporting#weight_total', :via => :get
  match 'reporting/update_weight', :to => 'reporting#update_weight', :via => :post
  match 'reporting/parcels_by_time_period', :to => 'reporting#parcels_by_time_period', :via => [:get, :post]
  match 'reporting/parcels_by_time_period_and_postcode', :to => 'reporting#parcels_by_time_period_and_postcode', :via => [:get, :post]  
  match 'reporting/households_with_multiple_parcels_by_time_period', :to => 'reporting#households_with_multiple_parcels_by_time_period', :via => [:get, :post]
  match 'reporting/food_donations_by_time_period', :to => 'reporting#food_donations_by_time_period', :via => [:get, :post]
  match 'reporting/food_donations_by_donor', :to => 'reporting#food_donations_by_donor', :via => [:get, :post]
    match 'reporting/inactive_households', :to => 'reporting#inactive_households', :via => [:get, :post]

  root :to => 'home#index'

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  
end

app/models/food_donation.rb
class FoodDonation < ActiveRecord::Base
  acts_as_reportable
  
  after_update :update_weight
  after_create :create_weight
  after_destroy :delete_weight  
  
  belongs_to :donor
  attr_accessible :donated, :donor_id, :weight
  validates :donor, :presence => true
  validates_numericality_of :weight, :greater_than => 0
  
  private
    def update_weight
      if self.weight_changed?
        ApplicationData.update_weight(self.weight - self.weight_was)
      end      
    end
    
    def create_weight
      ApplicationData.update_weight(self.weight)
    end
    
    def delete_weight
      ApplicationData.update_weight(-self.weight)
    end
end

app/controllers/food_donations_controller.rb
class FoodDonationsController < ApplicationController
  # GET /food_donations
  # GET /food_donations.json
  def index
    @food_donations = FoodDonation.paginate(:page => params[:page], :per_page => 10).order("created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @food_donations }
    end
  end

  # GET /food_donations/1
  # GET /food_donations/1.json
  def show
    @food_donation = FoodDonation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @food_donation }
    end
  end

  # GET /food_donations/new
  # GET /food_donations/new.json
  def new
    @food_donation = FoodDonation.new
    @food_donation.donated = Date.today
    
    if params[:donor]
      @food_donation.donor = Donor.find(params[:donor])
    end    

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @food_donation }
    end
  end

  # GET /food_donations/1/edit
  def edit
    @food_donation = FoodDonation.find(params[:id])
  end

  # POST /food_donations
  # POST /food_donations.json
  def create    
    respond_to do |format|
      if create_food_donation
        format.html { redirect_to @food_donation, notice: 'Food donation was successfully created.' }
        format.json { render json: @food_donation, status: :created, location: @food_donation }
      else
        format.html { render action: "new" }
        format.json { render json: @food_donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /food_donations/1
  # PUT /food_donations/1.json
  def update    
    @food_donation = FoodDonation.find(params[:id])
    
    respond_to do |format|
      if update_food_donation
        format.html { redirect_to @food_donation, notice: 'Food donation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @food_donation.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update_food_donation
    begin
      return @food_donation.update_attributes(params[:food_donation])
    rescue ActiveRecord::RecordInvalid => exc
      @food_donation.errors[:unexpected] = exc.message
      return false
    end
  end
  
  def create_food_donation
    begin
      @food_donation = FoodDonation.new(params[:food_donation])
      return @food_donation.save
    rescue ActiveRecord::RecordInvalid => exc
      @food_donation.errors[:unexpected] = exc.message
      return false
    end
  end  

  # DELETE /food_donations/1
  # DELETE /food_donations/1.json
  def destroy
    @food_donation = FoodDonation.find(params[:id])
    @food_donation.destroy

    respond_to do |format|
      format.html { redirect_to food_donations_url }
      format.json { head :no_content }
    end
  end
    
  def is_empty(h) 
    h.each_value { |value|
      if value.is_a?(Hash) 
        return false if !is_empty(value)
      else
        return false if !value.empty?
      end      
    }
    return true
  end
end

app/helpers/food_donations_helper.rb
module FoodDonationsHelper

end

app/views/food_donations/_form.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>
<% @food_donation.errors.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <%= content_tag :div, t(name) + " " + msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

<%= form_for @food_donation, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :donated, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :donated, :class => 'text_field', 'data-behaviour' => 'datepicker' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :donor_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :donor_id, Donor.order(:name), :id, :name, { :prompt => true } %>
    </div>
  </div> 
  <div class="control-group">
    <%= f.label :weight, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :weight, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                food_donations_path, :class => 'btn' %>
  </div>
<% end %>

app/views/food_donations/edit.html.erb
<%- model_class = @food_donation.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/food_donations/index.html.erb
<%- model_class = FoodDonation.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:donated) %></th>
      <th><%= model_class.human_attribute_name(:donor_id) %></th>
      <th><%= model_class.human_attribute_name(:weight) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
	<%= page_entries_info @food_donations %>
	<%= will_paginate @food_donations, :renderer => BootstrapPagination::Rails %>
    <% @food_donations.each do |food_donation| %>
      <tr>
        <td><%= link_to food_donation.id, food_donation_path(food_donation) %></td>
        <td><%= food_donation.donated %></td>
        <td><%= food_donation.donor %></td>
        <td><%= food_donation.weight %></td>
        <td><%=l food_donation.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_food_donation_path(food_donation), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      food_donation_path(food_donation),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_food_donation_path,
            :class => 'btn btn-primary' %>

app/views/food_donations/new.html.erb
<%- model_class = @food_donation.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/food_donations/show.html.erb
<%- model_class = @food_donation.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:donated) %>:</strong></dt>
  <dd><%= @food_donation.donated %></dd>
  <dt><strong><%= model_class.human_attribute_name(:donor_id) %>:</strong></dt>
  <dd><%= @food_donation.donor %></dd>
  <dt><strong><%= model_class.human_attribute_name(:weight) %>:</strong></dt>
  <dd><%= @food_donation.weight %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              food_donations_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_food_donation_path(@food_donation), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              food_donation_path(@food_donation),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>