config/routes.rb
FoodBank::Application.routes.draw do

  resources :users
  resources :user_sessions

  resources :food_parcels do
    
  end

  resources :expenditures

  resources :food_donations do

  end

  resources :products

  resources :financial_donations

  resources :donors

  resources :addresses
  resources :referring_agencies
  
  resources :households do
    resources :other_occupants
  end
  
  match 'reporting/weight_total', :to => 'reporting#weight_total', :via => :get
  match 'reporting/update_weight', :to => 'reporting#update_weight', :via => :post
  match 'reporting/parcels_by_time_period', :to => 'reporting#parcels_by_time_period', :via => [:get, :post]
  match 'reporting/parcels_by_time_period_and_postcode', :to => 'reporting#parcels_by_time_period_and_postcode', :via => [:get, :post]  
  match 'reporting/households_with_multiple_parcels_by_time_period', :to => 'reporting#households_with_multiple_parcels_by_time_period', :via => [:get, :post]
  match 'reporting/food_donations_by_time_period', :to => 'reporting#food_donations_by_time_period', :via => [:get, :post]
  match 'reporting/food_donations_by_donor', :to => 'reporting#food_donations_by_donor', :via => [:get, :post]
    match 'reporting/inactive_households', :to => 'reporting#inactive_households', :via => [:get, :post]

  root :to => 'home#index'

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  
end

app/models/other_occupant.rb
class OtherOccupant < Occupant
  RELATIONSHIP = { spouse: 0, partner: 1, child: 2, dependant: 3, other: 4 }
  
  belongs_to :household
  
  def self.RELATIONSHIP 
    RELATIONSHIP
  end
  
  def relationship_to_primary
    RELATIONSHIP.key(read_attribute(:relationship_to_primary))
  end
  
  def relationship_to_primary=(r)
    write_attribute(:relationship_to_primary, RELATIONSHIP[r])
  end
  
  attr_accessible :relationship_to_primary
end

app/controllers/other_occupants_controller.rb
class OtherOccupantsController < ApplicationController
  # GET /other_occupants
  # GET /other_occupants.json
  def index
    @household = Household.find(params[:household_id])
    @occupants = @household.other_occupants

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @occupants }
    end
  end

  # GET /other_occupants/1
  # GET /other_occupants/1.json
  def show
    @household = Household.find(params[:household_id])
    @occupant = OtherOccupant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @occupant }
    end
  end

  # GET /other_occupants/new
  # GET /other_occupants/new.json
  def new
    @household = Household.find(params[:household_id])
    @occupant = @household.other_occupants.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @occupant }
    end
  end

  # GET /other_occupants/1/edit
  def edit
    @household = Household.find(params[:household_id])
    @occupant = OtherOccupant.find(params[:id])
  end

  # POST /other_occupants
  # POST /other_occupants.json
  def create
    @household = Household.find(params[:household_id])
    @occupant = @household.other_occupants.build(params[:other_occupant])    

    respond_to do |format|
      if @occupant.save
        format.html { redirect_to :action => :index, notice: 'Occupant was successfully created.' }
        format.json { render json: @occupant, status: :created, location: @occupant }
      else
        format.html { render action: "new" }
        format.json { render json: @occupant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /other_occupants/1
  # PUT /other_occupants/1.json
  def update
    @household = Household.find(params[:household_id])
    @occupant = OtherOccupant.find(params[:id])

    respond_to do |format|
      if @occupant.update_attributes(params[:other_occupant])
        format.html { redirect_to [@household, @occupant], notice: 'Occupant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @occupant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /other_occupants/1
  # DELETE /other_occupants/1.json
  def destroy
    @household = Household.find(params[:household_id])
    @occupant = OtherOccupant.find(params[:id])
    @occupant.destroy

    respond_to do |format|
      format.html { redirect_to household_other_occupants_url }
      format.json { head :no_content }
    end
  end
end

app/views/other_occupants/_form.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>
<% @occupant.errors.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <%= content_tag :div, t(name) + " " + msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

<%= form_for [@household, @occupant], :html => { :class => 'form-horizontal' } do |f| %>

  <%= render :partial => 'common/occupant_fields', :locals => { :occupant_form => f } %>
  <div class="control-group">
    <%= f.label :relationship_to_primary, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :relationship_to_primary, OtherOccupant.RELATIONSHIP.inject({}) {|h, (k, v)| h[t(k)] = v; h}, :class => 'text_field' %>
    </div>
  </div>
  
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                household_other_occupants_path, :class => 'btn' %>
  </div>
<% end %>

app/views/other_occupants/edit.html.erb
<%- model_class = @occupant.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/other_occupants/index.html.erb
<%- model_class = OtherOccupant.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:forename) %></th>
      <th><%= model_class.human_attribute_name(:surname) %></th>
      <th><%= model_class.human_attribute_name(:sex) %></th>
      <th><%= model_class.human_attribute_name(:date_of_birth) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @occupants.each do |occupant| %>
      <tr>
        <td><%= link_to occupant.id, household_other_occupant_path(@household, occupant) %></td>
        <td><%= occupant.title %></td>
        <td><%= occupant.forename %></td>
        <td><%= occupant.surname %></td>
        <td><%= occupant.sex %></td>
        <td><%= occupant.date_of_birth %></td>
        <td><%=l occupant.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_household_other_occupant_path(@household, occupant), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      household_other_occupant_path(@household, occupant),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_household_other_occupant_path,
            :class => 'btn btn-primary' %>
<%= link_to t('.return', :default => t("helpers.links.return")),
            household_path(@household),
            :class => 'btn' %>

app/views/other_occupants/new.html.erb
<%- model_class = @occupant.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/other_occupants/show.html.erb
<%- model_class = @occupant.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @occupant.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:forename) %>:</strong></dt>
  <dd><%= @occupant.forename %></dd>
  <dt><strong><%= model_class.human_attribute_name(:surname) %>:</strong></dt>
  <dd><%= @occupant.surname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sex) %>:</strong></dt>
  <dd><%= @occupant.sex %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date_of_birth) %>:</strong></dt>
  <dd><%= @occupant.date_of_birth %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              household_other_occupants_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_household_other_occupant_path(@household, @occupant), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              household_other_occupant_path(@household, @occupant),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>