config/routes.rb
FoodBank::Application.routes.draw do

  resources :users
  resources :user_sessions

  resources :food_parcels do
    
  end

  resources :expenditures

  resources :food_donations do

  end

  resources :products

  resources :financial_donations

  resources :donors

  resources :addresses
  resources :referring_agencies
  
  resources :households do
    resources :other_occupants
  end
  
  match 'reporting/weight_total', :to => 'reporting#weight_total', :via => :get
  match 'reporting/update_weight', :to => 'reporting#update_weight', :via => :post
  match 'reporting/parcels_by_time_period', :to => 'reporting#parcels_by_time_period', :via => [:get, :post]
  match 'reporting/parcels_by_time_period_and_postcode', :to => 'reporting#parcels_by_time_period_and_postcode', :via => [:get, :post]  
  match 'reporting/households_with_multiple_parcels_by_time_period', :to => 'reporting#households_with_multiple_parcels_by_time_period', :via => [:get, :post]
  match 'reporting/food_donations_by_time_period', :to => 'reporting#food_donations_by_time_period', :via => [:get, :post]
  match 'reporting/food_donations_by_donor', :to => 'reporting#food_donations_by_donor', :via => [:get, :post]
    match 'reporting/inactive_households', :to => 'reporting#inactive_households', :via => [:get, :post]

  root :to => 'home#index'

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  
end

app/models/household.rb
class Household < ActiveRecord::Base
  acts_as_reportable
  
  def to_s
    self.primary_occupant.to_s + ", " + self.address.to_s
  end
  
  has_one :address, :dependent => :destroy
  has_one :primary_occupant, :dependent => :destroy
  has_many :other_occupants, :dependent => :destroy
  has_many :food_parcels
  accepts_nested_attributes_for :address, :allow_destroy => true
  accepts_nested_attributes_for :primary_occupant, :allow_destroy => true
  attr_accessible :disability, :reason, :referral_date, :address_attributes, :primary_occupant_attributes, :number_of_adults, :number_of_oaps, :number_of_babies, :baby_nappy_sizes, :number_of_small_children, :small_child_nappy_sizes, :number_of_children, :cooker, :microwave, :kettle, :no_facilities, :dietary_requirements, :comments, :food_parcels
  
  validates_associated :address
  validates_associated :primary_occupant
end

app/controllers/households_controller.rb
class HouseholdsController < ApplicationController
  # GET /households
  # GET /households.json
  def index
    #@households = Household.paginate :include => "primary_occupant", :order => "occupants.surname, occupants.forename", :page => params[:page], :per_page => 10
    
    all_houses = Household.eager_load(:primary_occupant, :address)
    if(!params.has_key? :letter)
      params[:letter]='A'
    end
    @households, @alphaParams = all_houses.alpha_paginate(params[:letter],{:default_field=>'A'}){|household| household.primary_occupant.surname}
        
    @autocomplete_items = all_houses.collect { |household| household.to_s }
    @household_matrix = Hash[all_houses.collect { |household| [household.to_s, household.id] }]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @households }
    end
  end

  # GET /households/1
  # GET /households/1.json
  def show
    @household = Household.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @household }
      format.xml { render xml: @household }
    end
  end

  # GET /households/new
  # GET /households/new.json
  def new
    @household = Household.new
    @household.referral_date = Date.today
    @household.build_address
    @household.build_primary_occupant
    @referral_date = Date.today

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @household }
    end
  end

  # GET /households/1/edit
  def edit
    @household = Household.find(params[:id])
  end

  # POST /households
  # POST /households.json
  def create
    @household = Household.new(params[:household])

    respond_to do |format|
      if @household.save
        format.html { redirect_to @household, notice: 'Household was successfully created.' }
        format.json { render json: @household, status: :created, location: @household }
      else
        format.html { render action: "new" }
        format.json { render json: @household.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /households/1
  # PUT /households/1.json
  def update
    @household = Household.find(params[:id])

    respond_to do |format|
      if @household.update_attributes(params[:household])
        format.html { redirect_to @household, notice: 'Household was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @household.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /households/1
  # DELETE /households/1.json
  def destroy
    @household = Household.find(params[:id])
    @household.destroy

    respond_to do |format|
      format.html { redirect_to households_url }
      format.json { head :no_content }
    end
  end  
end

app/helpers/households_helper.rb
module HouseholdsHelper
  def prepare_occupant(occupant)
    occupant.contact_information ||= ContactInformation.new
    occupant
  end
end

app/views/households/_form.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>
<% @household.errors.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <%= content_tag :div, t(name) + " " + msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

<%= form_for @household, :html => { :class => 'form-horizontal', :autocomplete => 'off' } do |household_form| %>
  <h3>Primary Occupant</h3>
  <br/>
  <% prepare_occupant(@household.primary_occupant) %>
  <%= household_form.fields_for :primary_occupant do |occupant_form| %>  
    <%= render :partial => 'common/occupant_fields', :locals => { :occupant_form => occupant_form } %>
  <% end %>
  <hr/>
  <h3>Address</h3>
  <br/>
  <%= household_form.fields_for :address do |address_form| %>
    <%= render :partial => 'common/address_fields', :locals => { :address_form => address_form } %>
  <% end %>
  <hr/>
  <h3>Household Details</h3>
  <br/>
  <div class="control-group">
    <%= household_form.label :number_of_adults, :class => 'control-label' %>
    <div class="controls">
      <%= household_form.text_field :number_of_adults, :class => 'text_field span1' %>
    </div>
    <%= household_form.label :number_of_oaps, :class => 'control-label' %>
    <div class="controls">
      <%= household_form.text_field :number_of_oaps, :class => 'text_field span1' %>
    </div>
    <%= household_form.label :number_of_babies, :class => 'control-label' %>
    <div class="controls controls-row">
      <%= household_form.text_field :number_of_babies, :class => 'text_field span1' %>
      <%= household_form.label :baby_nappy_sizes, :class => 'control-label' %>
      <%= household_form.text_field :baby_nappy_sizes, :class => 'text_field span1' %>
    </div>
    <%= household_form.label :number_of_small_children, :class => 'control-label' %>
    <div class="controls controls-row">
      <%= household_form.text_field :number_of_small_children, :class => 'text_field span1' %>
      <%= household_form.label :small_child_nappy_sizes, :class => 'control-label' %>
      <%= household_form.text_field :small_child_nappy_sizes, :class => 'text_field span1' %>
    </div>
    <%= household_form.label :number_of_children, :class => 'control-label' %>
    <div class="controls">
      <%= household_form.text_field :number_of_children, :class => 'text_field span1' %>
    </div>
  </div>
  <div class="control-group">
    <%= household_form.label :disability, :class => 'control-label' %>
    <div class="controls">
      <%= household_form.check_box :disability, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= household_form.label :cooking_facilities, :class => 'control-label' %>
    <div class="controls">
      <label class="checkbox inline">
        <%= household_form.check_box :cooker, :class => 'check_box' %><%= t(:cooker) %>
      </label>
      <label class="checkbox inline">
        <%= household_form.check_box :microwave, :class => 'check_box' %><%= t(:microwave) %>
      </label>
      <label class="checkbox inline">
        <%= household_form.check_box :kettle, :class => 'check_box' %><%= t(:kettle) %>
      </label>      
      <label class="checkbox inline">
        <%= household_form.check_box :no_facilities, :class => 'check_box' %><%= t(:no_facilities) %>
      </label>
    </div>
  </div>
  <div class="control-group">
    <%= household_form.label :reason, :class => 'control-label' %>
    <div class="controls">
      <%= household_form.text_area :reason, :rows => 3, :class => 'text_area span5' %>
    </div>
  </div>
  <div class="control-group">
    <%= household_form.label :dietary_requirements, :class => 'control-label' %>
    <div class="controls">
      <%= household_form.text_area :dietary_requirements, :rows => 3, :class => 'text_area span5' %>
    </div>
  </div>
  <div class="control-group">
    <%= household_form.label :comments, :class => 'control-label' %>
    <div class="controls">
      <%= household_form.text_area :comments, :rows => 3, :class => 'text_area span5' %>
    </div>
  </div>
  <div class="control-group">
    <%= household_form.label :referral_date, :class => 'control-label' %>
    <div class="controls">
      <%= household_form.text_field :referral_date, :class => 'text_field', 'data-behaviour' => 'datepicker' %>
    </div>
  </div>

  <div class="form-actions">
    <%= household_form.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                households_path, :class => 'btn' %>
  </div>
<% end %>

app/views/households/edit.html.erb
<%- model_class = @household.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/households/index.html.erb
<%- model_class = Household.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<form class="form-horizontal" id="household-form">
  <div class="household_controls">
    <input id="household-form-typeahead" name="name" type="text" class="input-med" data-provide="typeahead" autocomplete="off"  placeholder="Type here to find a household...">
    <input id="household-form-id" name="id" type="hidden" autocomplete="off">
    <input id="household-form-submit" type="submit" value="Go To Household" class="btn btn-primary">
    <%= link_to t('.new_household', :default => t("helpers.links.new_household")),
                new_household_path, :class => 'btn btn-primary' %>
  </div>
</form>

<%= javascript_tag "var autocomplete_items = #{ @autocomplete_items.to_json };" %>
<%= javascript_tag "var household_matrix = #{ @household_matrix.to_json };" %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:primary_occupant) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:parcels) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
	<!-- %= page_entries_info @households % -->
	<!-- %= will_paginate @households, :renderer => BootstrapPagination::Rails % -->
	<%= alphabetical_paginate @alphaParams %>
	<br/>
	<div id="pagination_table">
    <% @households.each do |household| %>
      <tr>
        <td><%= link_to household.primary_occupant, household_path(household) %></td>
        <td><%= link_to household.address, household_path(household) %></td>
        <td><%= link_to household.food_parcels_count, household_path(household) %></td>
        <td><%=l household.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_household_path(household), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      household_path(household),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
	</div>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_household_path,
            :class => 'btn btn-primary' %>

app/views/households/new.html.erb
<%- model_class = @household.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/households/show.html.erb
<%- model_class = @household.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:occupant) %>:</strong></dt>
  <dd><%= @household.primary_occupant %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @household.address %></dd>  
  <dt><strong><%= model_class.human_attribute_name(:reason) %>:</strong></dt>
  <dd><%= @household.reason %></dd>
  <dt><strong><%= model_class.human_attribute_name(:disability) %>:</strong></dt>
  <dd><%= @household.disability %></dd>
  <dt><strong><%= model_class.human_attribute_name(:referral_date) %>:</strong></dt>
  <dd><%= @household.referral_date %></dd>
</dl>

<h4>Food Parcels</h4>

<table border="2" width="50%">
	<tr>
		<th>Date</th><th>Weight</th><th/>
	</tr>
	<% for parcel in @household.food_parcels do %>
		<tr>
			<td align="center"><%= parcel.date %></td>
			<td align="center"><%= parcel.weight %></td>
			<td align="center"><%= link_to 'View...', food_parcel_path(parcel) %></td>
		</tr>
	<% end %>
</table>

<br/>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              households_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_household_path(@household), :class => 'btn' %>
  <%-# = link_to t(:manage_other_occupants), household_other_occupants_path(@household), :class => 'btn' -%>
  <%= link_to t(:create_food_parcel), new_food_parcel_path(:household => @household), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              household_path(@household),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>